In [1]:
import numpy as np
import pandas as pd

### How to create an numpy array?
#### We can create numpy arrays from native python tuples or lists

In [4]:
t=(1,2,3)
a=np.array(t,dtype= 'int') #dtpye表示数据类型
a

array([1, 2, 3])

In [5]:
list1 = [1,2,3]
a = np.array(list1,dtype='int')
a

array([1, 2, 3])

In [9]:
list2 = [4.2,5.1,6.3]

In [10]:
b=np.array([list1,list2])
b  #list1和list2数据类型自动兼容

array([[1. , 2. , 3. ],
       [4.2, 5.1, 6.3]])

In [11]:
b.dtype #确定numpy array的数据类型

dtype('float64')

In [12]:
#虚数
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [16]:
c.shape #看数组的维数

(2, 2)

#### Create Special Arrays

In [14]:
#2*2的全零矩阵
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [18]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.empty([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#5*5对角是1的矩阵
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
#2开始10结束每隔两个，不包括10
np.arange(2,10,2)

array([2, 4, 6, 8])

In [16]:
np.linspace(0,10,3) # 3 numbers from 0 to 10，三个数间隔相同，包括10

array([ 0.,  5., 10.])

#### Arithmetic Operators

In [18]:
a = np.array( [[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
a*a #位置相同的数自己乘自己

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [ ]:
a+a

In [19]:
1/a

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

#### Matrix operations

In [6]:
A = np.array( [[1,3],[0,1]] )
B = np.array( [[2,2],[3,4]] )

In [7]:
A*B

array([[2, 6],
       [0, 4]])

In [8]:
A.dot(B) #矩阵相乘

array([[11, 14],
       [ 3,  4]])

In [9]:
np.dot(A,B) #矩阵相乘

array([[11, 14],
       [ 3,  4]])

In [ ]:
np.add(A,B) #矩阵相加

#### Other Operations

In [10]:
# np.random.random 是在半开放区间[0.0, 1.0) 之间生成随机数字
# Return random floats in the half-open interval [0.0, 1.0).

a = np.random.random([3,3]) 
a

array([[0.10292191, 0.37386972, 0.06576732],
       [0.33456414, 0.62356389, 0.5103046 ],
       [0.65494428, 0.6433748 , 0.25790511]])

In [12]:
# np.random.randn 是一个服从高斯分布的矩阵
np.random.randn(3,3) 

array([[-0.46698753,  1.69025617,  1.82626028],
       [ 0.59928188,  1.54158201, -0.74814338],
       [-0.91385983,  0.66897464,  0.90970255]])

In [13]:
#a中的元素求和
a.sum()

3.5672157667551874

In [14]:
a.min()

0.06576731781789935

In [15]:
a.max()

0.6549442770745738

In [21]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# 关于 axis： axis=0 是对每一列操作  axis=1 是对每一行操作

In [22]:
b.sum(axis=0) # sum of each column

array([60, 66, 72, 78])

In [20]:
b.sum(axis=1) # sum of each row

array([ 6, 22, 38, 54, 70, 86])

In [22]:
b.min(axis=1) # min of each row

array([ 0,  4,  8, 12, 16, 20])

In [23]:
b.cumsum(axis=1) #每一行累加

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38],
       [12, 25, 39, 54],
       [16, 33, 51, 70],
       [20, 41, 63, 86]])

#### One_dimensional arrays

In [27]:
a= np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [25]:
# 我们从0开始数 0,1,2,3,4,5 第5个位置 对应的元素是 25

In [26]:
a[5]

25

In [27]:
a[2]

4

In [28]:
#slicing
a[2:6]

array([ 4,  9, 16, 25])

In [28]:
a[0:3] = 100
a

array([100, 100, 100,   9,  16,  25,  36,  49,  64,  81])

In [29]:
a_slice = a[0:5]
a_slice

array([100, 100, 100,   9,  16])

In [30]:
# 注意： 当我们选取部分 np array 的时候，我们创建了一个view。
# 换句话说，我们没有copy以前的值，而是直接改了原来的 array 

a_slice[0] = 233
print(a_slice)
print(a)

[233 100 100   9  16]
[233 100 100   9  16  25  36  49  64  81]


In [33]:
# 如果不想对原来的 array 进行修改，我们可以把选取的部分 copy 出来
a_slice_2=a[0:5].copy()
a_slice_2[0]=500
print(a_slice_2)
print(a)

[500 100 100   9  16]
[233 100 100   9  16  25  36  49  64  81]


### Multidimensional arrays

In [43]:
def f(x,y):
    return 4 * x + y
# derive from locations of the matrix
#[[00],[01],[10],[11],[20],[21]]
b = np.fromfunction (f,(3,2),dtype=int) #np.fromfunction 表示根据方程创建array
b

array([[0, 1],
       [4, 5],
       [8, 9]])

In [44]:
b[0]

array([0, 1])

In [39]:
b[1][0]

4

In [40]:
b[1,0]

4

In [ ]:
b[:,1]#选择所有的行以及第2列

In [41]:
c=np.zeros([5,5])
c 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
column_length=c.shape[1]#代表c array的列数
column_length

5

In [45]:
for i in range(column_length):
    c[i]=i
    print(c[i])

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
[3. 3. 3. 3. 3.]
[4. 4. 4. 4. 4.]


In [46]:
c 

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

#### Boolean Indexing

In [47]:
week_days=np.array(['Monday','Tuesday','Wednesday','Thursday','Friday'])

In [48]:
work_time=np.round(np.random.randn(5,5)+8.0,2)

In [49]:
work_time

array([[7.16, 6.68, 8.64, 8.26, 8.37],
       [8.24, 7.84, 8.63, 8.23, 7.7 ],
       [8.35, 6.83, 7.5 , 6.83, 9.76],
       [5.09, 8.05, 8.08, 7.86, 6.46],
       [8.88, 6.93, 7.1 , 7.86, 7.06]])

In [50]:
week_days=='Tuesday'

array([False,  True, False, False, False])

In [51]:
work_time[week_days=='Tuesday']

array([[8.24, 7.84, 8.63, 8.23, 7.7 ]])

### Matix Operations II

In [52]:
import numpy as np

In [63]:
a = np.array([[1,2,3],[3,4,5]],dtype='float')
a

array([[1., 2., 3.],
       [3., 4., 5.]])

In [54]:
a.T # a.T 的意思是 把所有的维度直接反过来： 比如原来的形状是 [1,2,4] 直接反过来变成 [4,2,1]

array([[1., 3.],
       [2., 4.],
       [3., 5.]])

In [57]:
a = np.array([[[1,2,3,0],[3,4,5,2]]])
a

array([[[1, 2, 3, 0],
        [3, 4, 5, 2]]])

In [58]:
a.shape #1堆2行4列

(1, 2, 4)

In [59]:
a.T #4堆2行1列

array([[[1],
        [3]],

       [[2],
        [4]],

       [[3],
        [5]],

       [[0],
        [2]]])

In [60]:
a.transpose()   #a.transpose可以指定到底要怎么变换：比如原来是 [1,2,4]， 
#可以指定转变的方式 [0,2,1]， 这个 [0,2,1] 的意思是 第一个维度不变，后两个维度交换
# 那么形状就变成了 [1,4,2]

array([[[1],
        [3]],

       [[2],
        [4]],

       [[3],
        [5]],

       [[0],
        [2]]])

In [64]:
np.dot(a.T,a)

array([[10., 14., 18.],
       [14., 20., 26.],
       [18., 26., 34.]])

In [65]:
# 求逆矩阵
# This calculates the inverse of a matrix
np.linalg.inv(np.dot(a.T,a))

array([[ 2.50199979e+14, -5.00399959e+14,  2.50199979e+14],
       [-5.00399959e+14,  1.00079992e+15, -5.00399959e+14],
       [ 2.50199979e+14, -5.00399959e+14,  2.50199979e+14]])

In [67]:
# 求是否相同
# Returns True if two arrays are element-wise equal within a tolerance : default 1e-08
?np.allclose

In [68]:
from numpy.linalg import inv 
a=np.array([[1.,2.],[3.,4.]])
inva=inv(a)

# here is to check if np.dot(a,inva) equals to I matrix
np.allclose(np.dot(a,inva),np.eye(2))

True

In [69]:
from numpy.linalg import * # *代表import numpy.linalg 真个包里的所有东西

In [71]:
eig(np.dot(a.T,a))#eig求矩阵特征值

(array([ 0.13393125, 29.86606875]), array([[-0.81741556, -0.57604844],
        [ 0.57604844, -0.81741556]]))

In [83]:
a = np.array([[1., 2.], [3., 4.]])
a

array([[1., 2.],
       [3., 4.]])

In [73]:
?np.trace # 算对角的和

Object `np.trace? # 算对角的和` not found.


In [77]:
np.trace(a)

5.0

In [78]:
a3d = np.arange(50).reshape([5,5,2])
a3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [79]:
a3d.transpose([0,2,1])#【0，1，2】表示三个位置都不变，【0，2，1】表示堆不变变成5堆2行5列

array([[[ 0,  2,  4,  6,  8],
        [ 1,  3,  5,  7,  9]],

       [[10, 12, 14, 16, 18],
        [11, 13, 15, 17, 19]],

       [[20, 22, 24, 26, 28],
        [21, 23, 25, 27, 29]],

       [[30, 32, 34, 36, 38],
        [31, 33, 35, 37, 39]],

       [[40, 42, 44, 46, 48],
        [41, 43, 45, 47, 49]]])

In [85]:
a.swapaxes(0,1)#把0轴1轴互换

array([[1., 3.],
       [2., 4.]])

In [87]:
np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))#反映出来的是在不同的位置，位置数的个数

array([1, 3, 1, 1, 0, 0, 0, 1])

In [88]:
np.bincount(np.array([1, 1, 2, 10, 2, 4, 7]))#返回11个数，因为最大数是10

array([0, 2, 2, 0, 1, 0, 0, 1, 0, 0, 1])